In [ ]:
print('hello')

hello


In [ ]:
a=1
b=2
print(a+b)

3


In [ ]:
# 변수 사용법과 입출력 배우기

# 예1: var1 이름으로 변수를 만들고 숫자 10 할당
var1=10
print('var1: ', var1)

var2=20
print('var2: ', var2)

var1:  10
var2:  20


In [ ]:
#다양한 연산자 사용
print( 1 + 2)
print( var1 + var2 )
print( var2 - var1 )
print( var1 * var2 )
print( var1 / var2 )

3
30
10
200
0.5


In [ ]:
# % 연산자(나머지 값 구하기) 사용
var5 = 3
var6 = 14
print('var6 / var5 나머지 값: ' , var6 % var5 )

var6 / var5 나머지 값:  2


In [ ]:
print('쑤쑤 열심히 하자!')

쑤쑤 열심히 하자!


In [ ]:
# print() 함수
# 출력문장 직접 쓰기
# 큰따음표, 작은따음표 상관없으며 같은 것만 쓰면 되지만 웹의 코드를 긁어올 때 오류가 날 수 있어 작은따음표를 사용하는 것이 좋음
print('이제부터 시작!')

str1 = '지금부터 화이팅!'
print('str1')
print(str1)
# 변수의 값을 출력하고 싶을 때는 따음표 하지 않기!

이제부터 시작!
str1
지금부터 화이팅!


In [ ]:
var1 = 100
print('var1 변수에 있는 값은 바로' , var1 , '입니다' )

var1 변수에 있는 값은 바로 100 입니다


In [ ]:
bab = 15
print('헉! 배터리가 %s 프로 밖에 안남았네ㅠㅠ' %bab)
# 콤마(,) 쓰지 않기!

헉! 배터리가 15 프로 밖에 안남았네ㅠㅠ


In [ ]:
up = 20
my = 10
print('친구 성적은 %s %%가 올랐는데 나도 %s %%라도 올랐으면 좋겠다' %(up, my))
# %를 문자로 넣고 싶으면 %(리터럴)%으로 써주면 됌

친구 성적은 20 %가 올랐는데 나도 10 %라도 올랐으면 좋겠다


In [ ]:
print('친구 성적은 {}%가 올랐는데 나도 {}%라도 올랐으면 좋겠다' .format(up,my))
# 요즘은 리터럴 방식 외 .format 형식을 많이 씀
# 값만 바꾸고 싶을 때 변수의 값은 그대로 두고 { } 안의 순서만 0, 1, 2 등 넣으면 됌

친구 성적은 20%가 올랐는데 나도 10%라도 올랐으면 좋겠다


In [ ]:
# 여러개의 플레이스 홀드 사용 가능
name = '박현수'
hobby = '걷기'
home = '포항'
str1 = '제 이름은 {}이고 취미는 {}이며 사는 지역은 {}입니다.'
print(str1.format(name, hobby, home))
# 프린트 내 포맷 사용 시 점(.)은 붙여서 써야함

제 이름은 박현수이고 취미는 걷기이며 사는 지역은 포항입니다.


In [ ]:
# input 함수로 정보 입력받기
menu = input()

마라탕


In [ ]:
# 안내멘트 함께 보기
menu_2 = input('오늘 저녁 뭐 먹지? ')
print(menu_2)

오늘 저녁 뭐 먹지? 마라샹궈
마라샹궈


In [ ]:
area_no = input('''
1. 미국  2. 영국  3. 독일  4. 체코  5. 스위스
6. 할슈타트  7. 크로아티아  8. 뉴질랜드

위 지역 중 검색을 원하는 지역의 번호를 입력하세요: 
''')
# 보기 입력할 때 작은 따음표 3개 입력 필요!


1. 미국  2. 영국  3. 독일  4. 체코  5. 스위스
6. 할슈타트  7. 크로아티아  8. 뉴질랜드

위 지역 중 검색을 원하는 지역의 번호를 입력하세요: 
5


In [ ]:
# input(), print() 활용
name = input('1. 이름을 입력하세요: ')
hobby = input('2. 취미를 입력하세요: ')

# 기본 출력
print(name, '님의 취미는' , hobby , '입니다.')

# 문자열 포맷팅
print('%s 님의 취미는 %s 입니다' %(name, hobby))

# 플레이스 홀드
s = '{} 님의 취미는 {} 입니다.'
print(s.format(name, hobby))

1. 이름을 입력하세요: 쑤
2. 취미를 입력하세요: 걷기
쑤 님의 취미는 걷기 입니다.
쑤 님의 취미는 걷기 입니다
쑤 님의 취미는 걷기 입니다.


In [ ]:
a = int(input('첫번째 숫자 입력: '))
b = int(input('두번째 숫자 입력: '))
print(a + b)
# int(인티저;정수) 선언을 하지 않으면 문자로 인식해서 문자 2개를 합친 결과가 나옴 ex(10, 20 > 1020)

첫번째 숫자 입력: 10
두번째 숫자 입력: 20
30


In [ ]:
a = float(input('첫번째 숫자 입력: '))
b = float(input('첫번째 숫자 입력: '))
# float 은 실수

첫번째 숫자 입력: 1.5
첫번째 숫자 입력: 3.5


In [ ]:
# 숫자 타입에서 많이 사용되는 주요 함수
# 1) round() - 반올림 함수

no1 = 3.45678
no2 = 3.56789
print('원래값: {} , 반올림 값: {}' .format(no1, round(no1)))
print('원래값: {} , 반올림 값: {}' .format(no2, round(no2)))

원래값: 3.45678 , 반올림 값: 3
원래값: 3.56789 , 반올림 값: 4


In [ ]:
# 1) round() - 반올림 함수, 소수점 이하 자리수 지정
no1 = 3
no2 = 5
print('반올림하기 전 원래값: ' , no2/no1)
print('소수 첫째자리 반올림: ' , round(no2/no1 , 1))
print('소수 둘째자리 반올림: ' , round(no2/no1 , 2))

반올림하기 전 원래값:  1.6666666666666667
소수 첫째자리 반올림:  1.7
소수 둘째자리 반올림:  1.67


In [ ]:
# trunc() - 버림 함수(많이 사용하지는 않는 편)
import math

no1 = 3
no2 = 5
print('버림하기 전 원래값: ' , no2/no1)
print('소수 첫째자리까지 버림하기: ' , math.trunc(no2 / no1))

버림하기 전 원래값:  1.6666666666666667
소수 첫째자리까지 버림하기:  1


In [ ]:
# ceil() - 큰 정수 찾기 함수(페이지 수 계산 시 많이 사용)
cnt = int(input('총 몇 건의 데이터를 수집할까요? '))
# 한 페이지 당 15건의 게시물이 있을 경우
page_cnt = math.ceil(cnt/15)

print('총 {} 페이지까지 데이터를 수집해야 합니다.' .format(page_cnt))
print(cnt/15)

총 몇 건의 데이터를 수집할까요? 100
총 7 페이지까지 데이터를 수집해야 합니다.
6.666666666666667


In [ ]:
# 작은 정수 찾기 - floor()
import math

no1 = 4.9
no2 = -5.1

print('원래 값:{} , 적용 값: {}' .format(no1 , math.floor(no1)))
print('원래 값:{} , 적용 값: {}' .format(no2 , math.floor(no2)))

원래 값:4.9 , 적용 값: 4
원래 값:-5.1 , 적용 값: -6


In [ ]:
# 슬라이싱 예제
# 대괄호 안의 영역을 지정할 때 시작은 0부터이나 :뒤의 숫자 -1 값까지 가져옴 ; 헷갈릴 경우 +1을 적어서 상쇄시켜주는 것이 편함

str1 = '파이썬완전쉽죠?'
print(str1)
print(str1[0])
print(str1[4])
print(str1[0:4])
print(str1[0:4+1])
print(str1[3:])
print(str1[:3])

파이썬완전쉽죠?
파
전
파이썬완
파이썬완전
완전쉽죠?
파이썬


In [ ]:
# lower() 함수 / upper() 함수 - 대소문자 변경 함수

str2 = 'PyThoN' # 대소문자가 섞여 있음
print(str2.lower())
print(str2.upper())

str3 = 'Park Hyeon Su' # 대소문자가 섞여 있음
print(str3.lower())
print(str3.upper())

python
PYTHON
park hyeon su
PARK HYEON SU


In [ ]:
# lstrip() / rstrip() / strip() - 여백 없애기

str3 = '               <- 여기에 공백 있어요.'
str4 = '여기에 공백 있어요.->                '
str5 = '         <-양쪽 끝에 공백 있어요.->             '

print(str3.lstrip())
print(str4.rstrip())
print(str5.strip())

<- 여기에 공백 있어요.
여기에 공백 있어요.->
<-양쪽 끝에 공백 있어요.->


In [ ]:
# replace()
str6 = '나는 잘하고 있는건가요?'
print(str6)
print(str6.replace('나' , '쑤'))

나는 잘하고 있는건가요?
쑤는 잘하고 있는건가요?


In [ ]:
# 의미없이 반복된 문자 삭제 가능
str6_2 = '응 아니야ㅎㅎㅎㅎㅎㅎ'
print(str6_2.replace('ㅎ',''))

응 아니야


In [ ]:
# split() : 특정 단어 혹은 기호를 기준으로 데이터 분리
# url, 전화번호 뽑아낼 때 많이 사용

tel = '02-345-6789'
print(tel.split('-'))
print(tel.split('-',1))

url = 'https://drive.google.com/drive/search?q=owner:me%20(type:application/vnd.google.colaboratory%20||%20type:application/vnd.google.colab)'
print(url.split('/'))

['02', '345', '6789']
['02', '345-6789']
['https:', '', 'drive.google.com', 'drive', 'search?q=owner:me%20(type:application', 'vnd.google.colaboratory%20||%20type:application', 'vnd.google.colab)']


In [ ]:
# len() - 요소가 몇개인지 파악

str1 = '파이썬 정말 좋아요!'
str2 = ['파이썬' , '인공지능' , '재밌다' , '힘내자']

print(len(str1))
print(len(str2))

11
4


In [ ]:
print('=' *30)
print('    문자열로 연산하기 코드')
print('=' *30)

    문자열로 연산하기 코드


In [ ]:
# list

hero = ['나타샤' , '2021' , '존멋']
print(hero)

['나타샤', '2021', '존멋']


In [ ]:
# append() - 데이터 맨 뒤에 추가
# insert() - 중간에 내용을 추가

list2 = ['첫째' , '둘째' , '셋째']
list2.append('append로 추가한 것')
list2.insert(2, 'insert로 추가한 것')
print(list2)

['첫째', '둘째', 'insert로 추가한 것', '셋째', 'append로 추가한 것']


In [ ]:
# del() / remove

print('삭제 전 목록: ' , list2)
del list2[2]
print('del로 삭제 후 목록: ' , list2)

list2.remove('append로 추가한 것')
print('remove로 삭제 후 목록: ' , list2)

삭제 전 목록:  ['첫째', '둘째', 'insert로 추가한 것', '셋째', 'append로 추가한 것']
del로 삭제 후 목록:  ['첫째', '둘째', '셋째', 'append로 추가한 것']
remove로 삭제 후 목록:  ['첫째', '둘째', '셋째']


In [ ]:
# sort() / reverse()
# 내림차순을 하고 싶은 경우 오름차순 먼저 정렬한 후 reverse 사용해야 함
# reverse는 순서만 뒤집어줌

list3 = [5, 1, 3, 6, 7]
list3.sort()
print('오름차순(기본)정렬: ' , list3)

list3.reverse()
print('내림차순 정렬: ' , list3)

list4 = ['banana' , 'apple' , 'cherry' , 'Apple']
list4.sort()
print('알파벳순 정렬: ' , list4)

list5 = ['모니카' , '허니제이' , '아이키' , '노제']
list5.sort()
print('가나다순 정렬: ' , list5)

오름차순(기본)정렬:  [1, 3, 5, 6, 7]
내림차순 정렬:  [7, 6, 5, 3, 1]
알파벳순 정렬:  ['Apple', 'apple', 'banana', 'cherry']
가나다순 정렬:  ['노제', '모니카', '아이키', '허니제이']


In [1]:
# 조건문, 반복문, 인공지능 알고리즘 등등 2021.12.22.일자 13:00 수업 예정

In [2]:
# if 조건문 유형 1
# 다양한 연산자들의 의미(== 같다 / != 같지 않다 / > 크다 / >= 크거나 같다 / < 작다 / <= 작거나 같다)
# 파이썬에서 if, 반복문 등 사용 시 'if 조건 :' 이후 실행문장의 들여쓰기 꼭 해야함!

In [3]:
# 조건문 예제 1번

name = input('조회할 사람의 이름을 입력하세요.')

if name == '박현수' :
  print('박현수입니다.')
  print('여자입니다.')
  print('수업중입니다.')

조회할 사람의 이름을 입력하세요.박현수
박현수입니다.
여자입니다.
수업중입니다.


In [4]:
# if 조건문 유형 2
# if 조건 : 
#    실행문장 1
# else :
#    실행문장 2

In [5]:
# 조건문 예제 2번

name = input('조회할 사람의 이름을 입력하세요.')

if name == '박현수' :
  print('박현수입니다.')
  print('여자입니다.')
  print('수업중입니다.')
else :
  print('박현수가 아니고 {} 입니다.' .format(name))
  print('성별이 무엇인가요?')
  print('무엇을 하고있나요?')

조회할 사람의 이름을 입력하세요.김모양
홍길동이 아니고 김모양 입니다.
성별이 무엇인가요?
무엇을 하고있나요?


In [6]:
# if 조건문 유형 3
# if 조건 1:
#    실행문장 1 ~.
# elif 조건 2:
#    실행문장 2 ~.
# elif 조건 3:
#    실행문장 3 ~.
# else 조건 4:
#    실행문장 4 ~.

# elif(엘즈이프)

In [8]:
# if 조건문 예제 3번
fruit = input('사과, 감, 자두 중에 하나를 입력하세요: ')

if fruit == '사과' : 
  print('사과입니다.')
elif fruit == '감' : 
  print('감입니다.')
elif fruit == '자두' : 
  print('자두입니다.')
else :
  print('사과, 감, 자두 중에서 입력하세요')

사과, 감, 자두 중에 하나를 입력하세요: 애플
사과, 감, 자두 중에서 입력하세요


In [18]:
# 예제 4 - and 연산자

jumsu = int(input('점수를 입력해주세요(0 ~ 100): '))

if jumsu >= 91 and jumsu <= 100 :
  print('A 등급입니다!')
elif jumsu >= 81 and jumsu <= 90 :
  print('B 등급입니다!')
elif jumsu >= 71 and jumsu <= 80 :
  print('C 등급입니다!')
elif jumsu > 100 or jumsu < 0 :
  print('측정할 수 없습니다.')
else :
  print('D 등급 입니다!')

점수를 입력해주세요(0 ~ 100): -3
측정할 수 없습니다.


In [20]:
# 예제 5 - or 연산자

answer = input('Y 또는 y를 입력하세요: ')
if answer == 'Y' or answer == 'y' :
  print('입력하신 문자는 {} 입니다.' .format(answer))
else :
  print('Y 또는 y를 입력하세요.')

Y 또는 y를 입력하세요: D
Y 또는 y를 입력하세요.


In [23]:
# 예제 6 - not 연산자

answer = input('Y 또는 y를 입력하세요: ')
if answer != 'Y' and answer != 'y' :
  print('입력하신 문자는 {} 입니다.' .format(answer))
else :
  print('Y 또는 y를 입력하셨네요.')

Y 또는 y를 입력하세요: n
입력하신 문자는 n 입니다.


In [27]:
# 예제 7 - 3의 배수이면 제곱으로, 아니면 0으로 출력하기

no1 = int(input('숫자를 입력하세요: '))
if no1%3 == 0 :
  print(no1**2)
else :
  print(no1*0)

숫자를 입력하세요: 12
144


In [31]:
fruits = input('사과, 감, 귤, 복숭아 중에 어떤 과일을 좋아하세요?: ')
if fruits == '복숭아' or fruits == '귤' :
  print('완전 좋아!')
elif fruits == '사과' or fruits == '감' :
  print('음~')
else :
  print('사과, 감, 귤, 복숭아 중 하나를 입력하세요!')

사과, 감, 귤, 복숭아 중에 어떤 과일을 좋아하세요?: 샤인머스켓
사과, 감, 귤, 복숭아 중 하나를 입력하세요!


In [34]:
# if문 종합정리1
# print('\n')은 줄넘김을 뜻함

menu = int(input('''
1. 짜장면 - 5,000원  2. 짬뽕 - 6,000원
3. 군만두 - 7,000원  4. 탕수육 - 8,000원

1. 위 메뉴 중 주문할 메뉴의 번호를 쓰세요: '''))
qty = int(input('2. 위 메뉴의 주문 수량을 쓰세요: '))
print('\n')

if menu == 1 :
  print('주문하신 메뉴는 짜장면, 주문 수량은 {}그릇, 주문금액은 {}원 입니다.' .format(qty, 5000*qty))
elif menu == 2 :
  print('주문하신 메뉴는 짬뽕, 주문 수량은 {}그릇, 주문금액은 {}원 입니다.' .format(qty, 6000*qty))
elif menu == 3 :
  print('주문하신 메뉴는 군만두, 주문 수량은 {}그릇, 주문금액은 {}원 입니다.' .format(qty, 7000*qty))
elif menu == 4 :
  print('주문하신 메뉴는 탕수육, 주문 수량은 {}그릇, 주문금액은 {}원 입니다.' .format(qty, 8000*qty))
else :
  print('메뉴 선택을 잘못하셨습니다.')


1. 짜장면 - 5,000원  2. 짬뽕 - 6,000원
3. 군만두 - 7,000원  4. 탕수육 - 8,000원

1. 위 메뉴 중 주문할 메뉴의 번호를 쓰세요: 2
2. 위 메뉴의 주문 수량을 쓰세요: 2


주문하신 메뉴는 짬뽕, 주문 수량은 2그릇, 주문금액은 12000원 입니다.


In [35]:
# for 반복문 활용하기

# for 변수 in 반복횟수 : 
#     실행할 문장 1
#     실행할 문장 2
#     실행할 문장 3

# i(index의 약자로 많이 쓰임)

In [37]:
# for 반복문 예제 1

for i in (1, 2, 3, 4, 5, 6) :
  print(i)

1
2
3
4
5
6


In [38]:
# for 반복문 예제 2

data = ['하나', '둘', '셋']

for i in data:
  print(i)

하나
둘
셋


In [40]:
# for 반복문 예제 3

data = ['엄마', '큰냐', '짠냐']

for i in data:
  print('{}는 우리집 구성원 입니다.' .format(i))

엄마는 우리집 구성원 입니다.
큰냐는 우리집 구성원 입니다.
짠냐는 우리집 구성원 입니다.


In [50]:
# for 반복문 예제 4

for i in range(1,5) :
  print('밥 {}그릇 주세요!' .format(i))

print('=' *30)

for i in range(1,5+1) :
  print('밥 {}그릇 주세요!' .format(i))

밥 1그릇 주세요!
밥 2그릇 주세요!
밥 3그릇 주세요!
밥 4그릇 주세요!
밥 1그릇 주세요!
밥 2그릇 주세요!
밥 3그릇 주세요!
밥 4그릇 주세요!
밥 5그릇 주세요!


In [49]:
# for문으로 구구단 출력하기

no = int(input('출력을 원하는 단을 입력하세요: '))

for i in range(1, 9+1) :
  print(no , 'X' , i , '=' , no*i)

print('=' *30)

for i in range(1, 19+1) :
  print(no , 'X' , i , '=' , no*i)

출력을 원하는 단을 입력하세요: 9
9 X 1 = 9
9 X 2 = 18
9 X 3 = 27
9 X 4 = 36
9 X 5 = 45
9 X 6 = 54
9 X 7 = 63
9 X 8 = 72
9 X 9 = 81
9 X 1 = 9
9 X 2 = 18
9 X 3 = 27
9 X 4 = 36
9 X 5 = 45
9 X 6 = 54
9 X 7 = 63
9 X 8 = 72
9 X 9 = 81
9 X 10 = 90
9 X 11 = 99
9 X 12 = 108
9 X 13 = 117
9 X 14 = 126
9 X 15 = 135
9 X 16 = 144
9 X 17 = 153
9 X 18 = 162
9 X 19 = 171


In [56]:
# for문 : 숫자 1개를 입력받아 1부터 해당 수까지 짝수 골라내기

no = int(input('숫자를 입력하세요: '))
for i in range(1, no+1) :
  if i%2 == 0 :
    print(i)

숫자를 입력하세요: 5
2
4


In [60]:
# for문 : 숫자 1개를 입력받아 1부터 해당 수까지 홀수 골라내기

no = int(input('숫자를 입력하세요: '))
for i in range(1, no+1) :
  if i%2 != 0 :
    print(i)

숫자를 입력하세요: 5
1
3
5


In [61]:
# for문 안에 for문이 들어간 형태
page_no = [1,2,3]
text_no = [1,2,3,4,5]

for a in page_no :
  print('\n')
  for b in text_no :
    print('{} 페이지의 {} 번 글입니다.' .format(a,b))



1 페이지의 1 번 글입니다.
1 페이지의 2 번 글입니다.
1 페이지의 3 번 글입니다.
1 페이지의 4 번 글입니다.
1 페이지의 5 번 글입니다.


2 페이지의 1 번 글입니다.
2 페이지의 2 번 글입니다.
2 페이지의 3 번 글입니다.
2 페이지의 4 번 글입니다.
2 페이지의 5 번 글입니다.


3 페이지의 1 번 글입니다.
3 페이지의 2 번 글입니다.
3 페이지의 3 번 글입니다.
3 페이지의 4 번 글입니다.
3 페이지의 5 번 글입니다.


In [62]:
# while 반복문 문법
# while 조건:
#       실행할 문장 1
#       실행할 문장 2
# 

In [68]:
# while 반복문 예제 1

no1 = 1
while no1<9 :
  print(no1)
  no1 += 2

print('=' *50)
print(' 문장의 순서에 따라 값이 달라질 수 있음을 알기!')
print('=' *50)

# while 반복문 예제 2

no1 = 0
while no1<9 :
  no1 += 2
  print(no1)

1
3
5
7
 문장의 순서에 따라 값이 달라질 수 있음을 알기!
2
4
6
8
10


In [69]:
# while문으로 구구단 출력하기

dan = int( input('출력을 원하는 단을 입력하세요: '))
no = 1

while no < 10 :
  print('{} X {} = {}' .format(dan, no, dan*no))
  no += 1

출력을 원하는 단을 입력하세요: 2
2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18


In [72]:
# break문(문장을 찾으면 멈춤)

snack = ['새우깡', '감자깡', '고구마깡', '옥수수깡', '밤깡']
for i in snack :
  if i == '밤깡' :
    break
  print(i, '내 최애')

새우깡 내 최애
감자깡 내 최애
고구마깡 내 최애
옥수수깡 내 최애


In [74]:
# continue문(문장을 찾더라도 제외하고 반복)

snack = ['새우깡', '감자깡', '고구마깡', '옥수수깡', '밤깡']
for i in snack :
  if i == '새우깡' :
    continue
  print(i, '내 최애')

감자깡 내 최애
고구마깡 내 최애
옥수수깡 내 최애
밤깡 내 최애


In [75]:
# 예외처리 예제 1

# 정상적인 경우
print('정상적인 경우')
no1 = int(input('숫자를 입력하세요: '))
print(no1)

# 예외가 발생한 경우
print('예외가 발생한 경우')
no2 = int(input('숫자를 입력하세요: '))
print(no2)

정상적인 경우
숫자를 입력하세요: 10
10
예외가 발생한 경우
숫자를 입력하세요: a


ValueError: ignored

In [78]:
# 예외처리 예제 2

# 예외가 발생한 경우
print('예외가 발생한 경우')
try: 
  no2 = int(input('숫자를 입력하세요: '))
except ValueError : 
  print('숫자를 입력하세요')
else :
  print(no2)

예외가 발생한 경우
숫자를 입력하세요: ㅁ
숫자를 입력하세요


In [81]:
# 예외처리 예제 3 - 1

no1 = 10
no2 = 0
print(no1 / no2)
# ZeroDivisionError가 발생

ZeroDivisionError: ignored

In [84]:
# 예외처리 예제 3 - 2

no1 = int(input('숫자를 입력하세요: '))
no2 = int(input('숫자를 입력하세요: '))
try :
  print(no1 / no2)
except ZeroDivisionError :
  print('0으로 나눌 수 없습니다.')
# ZeroDivisionError가 발생


숫자를 입력하세요: 15
숫자를 입력하세요: 5
3.0


In [89]:
# 예외처리 예제 3 - 3(어떤 오류가 발생할 지 모르는 경우)

no1 = int(input('숫자를 입력하세요: '))
no2 = int(input('숫자를 입력하세요: '))
try :
  print(no1 / no2)
except  :
  print('값을 확인해주세요.')

숫자를 입력하세요: 10
숫자를 입력하세요: 0
값을 확인해주세요.


In [91]:
# 예외처리 예제 4

try:
  no = int(input('숫자만 입력하세요: '))
except :
  print('꼭 숫자만 입력해주세요.')
else :
  print('입력하신 숫자는 {}입니다.' .format(no))

숫자만 입력하세요: 10
입력하신 숫자는 10입니다.


In [93]:
# 예외처리 - finally 사용

try :
  num = int(input('숫자를 입력하세요.'))
except ValueError :
  print('숫자가 아닙니다.')
else :
  print('입력한 숫자는 %s입니다.' %num)
finally :
  print('finally는 무조건 실행됩니다.')

숫자를 입력하세요.abc
숫자가 아닙니다.
finally는 무조건 실행됩니다.


In [94]:
# numpy 모듈 기본

import numpy as np

# numpy를 사용하기 위해 array 형태로 만들기

data1 = [1,2,3,4,5]
array1 = np.array(data1)
print(array1)

# array의 크기와 형태 확인
array1.shape

[1 2 3 4 5]


(5,)

In [96]:
import numpy as np

# numpy를 사용하기 위해 array 형태로 만들기

data2 = [1,2,3,4,5.5]
array2 = np.array(data2)
print(array2)

# array의 크기와 형태 확인
array2.shape

# array는 같은 형태의 데이터만 정리, 나열할 수 있음(실수는 실수, 정수는 정수, 문자는 문자)
# 문자, 실수, 정수 순의 우선권을 가짐

[1.  2.  3.  4.  5.5]


(5,)

In [97]:
import numpy as np

# numpy를 사용하기 위해 array 형태로 만들기

data3 = [1,2,3,4,'배고파']
array3 = np.array(data3)
print(array3)

# array의 크기와 형태 확인
array3.shape

['1' '2' '3' '4' '배고파']


(5,)

In [98]:
# array() 함수 안에 리스트를 바로 사용

array4 = np.array([1,2,3,4,5])
print(array4)

[1 2 3 4 5]


In [99]:
# 데이터 타입 확인하기

print('array1: ' , array1.dtype)
print('array2: ' , array2.dtype)
print('array3: ' , array3.dtype)
print('array4: ' , array4.dtype)

array1:  float64
array2:  float64
array3:  <U21
array4:  int64


In [101]:
# 0으로 구성된 N차원 배열 생성(실수 형태로 정렬)

print(np.zeros( (3,4) ))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [102]:
# 1로 구성된 N차원 배열 생성(정수 형태로 정렬)

print(np.ones( (3,4) , dtype=np.int16 ))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [107]:
# arrange() - N만큼 연속적으로 차이나는 배열 생성

print(np.arange(1, 30, 5))
print(np.arange(10, 31, 5))

[ 1  6 11 16 21 26]
[10 15 20 25 30]


In [112]:
# linspace() - N등분하기
x = np.linspace(0, 99, 100) # 0~99까지 100등분
print(x)
print('\n')
print('=' *50 )
print('\n')
x = np.linspace(1, 100, 10) # 0~99까지 100등분
print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]




[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [114]:
# 2차원 array 생성하기

array5 = np.array( [ [1,2,3], [3,4,5], [5,6,7] ] )
print(array5)
array5.shape

# np.array() 안에 대괄호 한번 더 입력해주어야함!

[[1 2 3]
 [3 4 5]
 [5 6 7]]


(3, 3)

In [118]:
# reshape() 차원을 변경하기

array6 = np.arange(12).reshape(4,3)
print(array6)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [119]:
# reshape() 차원을 변경하기 2

array7 = array6.reshape(2,6)
print(array7)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [120]:
# 비정형 데이터를 정형 데이터로 바꿔주는 Pandas

import pandas as pd

# 기본문법
# Series 첫자 무조건 대문자로 작성!
# 구글코랩을 사용하기 때문에 print 사용하지 않고 변수명만 사용 가능

member = pd.Series(['모니카', '노제', '아이키', '리헤이'])
member

0    모니카
1     노제
2    아이키
3    리헤이
dtype: object

In [121]:
import pandas as pd

# 기본문법 2
member = pd.Series(['모니카', '노제', '아이키', '리헤이'],
                   index = ['1번', '2번', '3번', '4번'])
member

1번    모니카
2번     노제
3번    아이키
4번    리헤이
dtype: object

In [124]:
# 딕셔너리 형(중괄호 사용)

sal_1 = { '모니카' : 100, '리헤이' : 90, '아이키' : 80 }
sal_2 = pd.Series(sal_1)
sal_2

모니카    100
리헤이     90
아이키     80
dtype: int64

In [125]:
import pandas as pd

member = pd.Series(['모니카', '노제', '아이키', '리헤이'],
                   index = ['1번', '2번', '3번', '4번'])
member

1번    모니카
2번     노제
3번    아이키
4번    리헤이
dtype: object

In [126]:
member['1번']

'모니카'

In [128]:
member[['3번','4번']]

3번    아이키
4번    리헤이
dtype: object

In [129]:
import pandas as pd
sal_1 = {'아이키' :100, '노제' : 90, '허니제이' : 80}
sal_2 = pd.Series(sal_1)
sal_2

아이키     100
노제       90
허니제이     80
dtype: int64

In [134]:
import pandas as pd
sal_3 = {'아이키' :10, '노제' : 20, '립제이' : 30}
sal_4 = pd.Series(sal_3)
sal_4

아이키    10
노제     20
립제이    30
dtype: int64

In [135]:
print(sal_2 + sal_4)

노제      110.0
립제이       NaN
아이키     110.0
허니제이      NaN
dtype: float64


In [137]:
# 딕셔너리와 리스트를 활용해 DataFrame 생성하기

member3 = {'번호' : ['1번','2번','3번'],
           '이름' : ['아이키', '립제이', '노제'],
           '생년' : [1995, 1997, 1999]}
member4 = pd.DataFrame(member3)
member4

번호   이름    생년
0  1번  아이키  1995
1  2번  립제이  1997
2  3번   노제  1999

In [138]:
# 딕셔너리와 리스트를 활용해 DataFrame 생성, 컬럼 순서 변경하기
member3 = {'번호' : ['1번','2번','3번'],
           '이름' : ['아이키', '립제이', '노제'],
           '생년' : [1995, 1997, 1999]}
member5 = pd.DataFrame(member3, columns=['번호', '생년', '이름'])
member5

번호    생년   이름
0  1번  1995  아이키
1  2번  1997  립제이
2  3번  1999   노제

In [139]:
import pandas as pd
no = ['1번','2번','3번']
name = ['아이키', '립제이', '노제']
birth = [1995, 1997, 1999]

member6 = pd.DataFrame()
member6['번호'] = no
member6['이름'] = name
member6['생년'] = birth

member6

번호   이름    생년
0  1번  아이키  1995
1  2번  립제이  1997
2  3번   노제  1999

In [142]:
# 생년 기준 내림차순

member6.sort_values( ['생년'], ascending = [False])

번호   이름    생년
2  3번   노제  1999
1  2번  립제이  1997
0  1번  아이키  1995

In [143]:
# 생년 기준 오름차순

member6.sort_values( ['생년'], ascending = [True])

번호   이름    생년
0  1번  아이키  1995
1  2번  립제이  1997
2  3번   노제  1999

In [146]:
from google.colab import files
myfile = files.upload()

Saving 부품구입대장.xlsx to 부품구입대장.xlsx


In [148]:
# merge 실습용 데이터 생성 1

import pandas as pd 
df_1 = {'학번' : ['1001','1002','1003'],
        '이름' : ['홍길동','일지매','전우치'],
        '키' : [180,175,168]}
stu_1 = pd.DataFrame(df_1)
stu_1

학번   이름    키
0  1001  홍길동  180
1  1002  일지매  175
2  1003  전우치  168

In [149]:
# merge 실습용 데이터 생성 2

import pandas as pd 
df_2 = {'학번' : ['1001','1002','1003'],
        '이름' : ['홍길동','일지매','전우치'],
        '몸무게' : [80,75,68]}
stu_2 = pd.DataFrame(df_2)
stu_2

학번   이름  몸무게
0  1001  홍길동   80
1  1002  일지매   75
2  1003  전우치   68

In [150]:
# 기본값 - merge 할 기준을 지정

pd.merge(stu_1, stu_2, how = 'left', left_on = '이름', right_on = '이름')

학번_x   이름    키  학번_y  몸무게
0  1001  홍길동  180  1001   80
1  1002  일지매  175  1002   75
2  1003  전우치  168  1003   68

In [151]:
# 기본값 - merge 할 기준을 지정

pd.merge(stu_1, stu_2, how = 'outer', left_on = '이름', right_on = '이름')

학번_x   이름    키  학번_y  몸무게
0  1001  홍길동  180  1001   80
1  1002  일지매  175  1002   75
2  1003  전우치  168  1003   68

In [152]:
pd.concat([stu_1 , stu_2],  axis = 0)

학번   이름      키   몸무게
0  1001  홍길동  180.0   NaN
1  1002  일지매  175.0   NaN
2  1003  전우치  168.0   NaN
0  1001  홍길동    NaN  80.0
1  1002  일지매    NaN  75.0
2  1003  전우치    NaN  68.0

In [153]:
pd.concat([stu_1 , stu_2],  axis = 1)

학번   이름    키    학번   이름  몸무게
0  1001  홍길동  180  1001  홍길동   80
1  1002  일지매  175  1002  일지매   75
2  1003  전우치  168  1003  전우치   68